### PR TITLE
Readme rewrite

### PR DESCRIPTION
**Pull request by dnystrom1**
Added two build scripts for Bob to review i.e. lanl-ats1 and lanl-cts1.  There are questions
that I need to discuss with Bob.

### CODE REVIEW

**Comment by rfbird** [comment]
Can we first document the combinations of options that are valid? i.e What does one select when doing a V8 build and how does a user figure that out?

**Comment by rfbird** [comment]
Can we merge my readme_rewrite to devel and have you point your PR at devel please?

**Comment by dnystrom1** [comment]
Sure.

**Comment by rfbird** [comment]
Closed as replaced by #46

**Pull request closed without merging**
