### PR TITLE
Catalyst particles

### PR DESCRIPTION
**Pull request by chetnieter**
This pull request gives the catalyst plugin in VPIC access to the particle data for use in visualization pipelines. Also included are some sample python scripts to create catalyst viz pipelines for the particle data. The changes included in #3 are also part of this request so if this request is accepted then #3 should be dropped.

### CODE REVIEW

**Comment by mkuchnik** [comment]
Are there any issues with this pull request preventing it from being merged? Catalyst support seems useful.

**Comment by chetnieter** [comment]
Unless @acbauer knows of any issues I think this can be merged. The Catalyst support is off by default so it shouldn't impact users not needed Catalyst.

**Comment by acbauer** [comment]
I don't know any issues. As Chet said, by default it is disabled and people that don't care about Catalyst may not even know it's there.

**Comment by rfbird** [comment]
Hey guys, sorry we've been a bit slow on this. As per the email that landed in @chetnieter inbox a week or two ago, we should hopefully be looking to get this merged in soon (pending some testing)

**Comment by mkuchnik** [comment]
Hi all, it seems "contourbenchmark.py" is missing from the catalyst sample "8preconnection.cxx". It may be worth checking to see if any such dependencies are left in before merging.

**Comment by chetnieter** [comment]
@mkuchnik I have modified `8preconnection.cxx` so it no longer refers the the non-existent `contourbenchmark.py`. The one catalyst python script it does refer too, `gridwriter.py` has been added to the scripts/catalyst directory.

**Comment by rfbird** [comment]
This is now, once again, under active development

**Comment by rfbird** [comment]
Closing this issue so a new issue can be re-opened by internal developer working on integrating this feature with required work flows

**Pull request closed without merging**
