### PR TITLE
Readme rewrite

### PR DESCRIPTION
**Pull request by rfbird**
I attempted to clean up the readme a little bit, to reflect the current state of things

@dnystrom1  could you add you 2c on how you would like to document options like  `USE_V4_SSE` ?

### CODE REVIEW

**Comment by dnystrom1** [comment]
So, how do I review the README changes and supplement them?  Do I clone VPIC and review/modify
the README.md file?  Or do I do something via the web interface?

**Comment by rfbird** [comment]
How I like to do it:

At the top there is a " Files changed 2" tab. Click that. That will show you something similar to an `xdiff` output (I like to click the "diff settings" in the top right and set it to "split)

You can then see the changes I made (green = added, red = deleted, etc). If you want to make any comments just click the "+" symbol that appears if you however over a line.

Let me know if that works out for you

**Comment by rfbird** [comment]
Just a reminder @dnystrom1 , this needs some attention when you have chance

I think we should merge what I have and add some documentation for the various allowable option combinations. I'll then generate intel and gcc scripts to do this

**Comment by rfbird** [comment]
Merging this one as it's been sitting around for a bit too long now. Let's try be better about code review in the future

**Pull request merged**
