### PR TITLE
ARM NEON Intrinsics Implementation and C++ Files

### PR DESCRIPTION
**Pull request by dnystrom1**
This pull request does the following:
1. Renames C implementation files to C++ implementation files with .cc extension.
2. Adds a V4 NEON intrinsics implementation for ARM TX2 clusters.
3. Various format changes, typo corrections, grammar corrections, white space deletion, etc that do not affect functionality.

### CODE REVIEW

**Comment by rfbird** [comment]
Is there a reason this is lumped into one PR not two or even three? (renaming, general fixes, neon)

**Comment by dnystrom1** [comment]
That was the simplest branch that I had for which I could submit the ARM NEON intrinsics work.  It would take some significant time to separate the work into either 2 or 3 branches to use for either 2 or 3 pull requests.

**Comment by rfbird** [comment]
OK. Let me spend some time figuring out why the tests don't pass and we can go from there

**Comment by rfbird** [comment]
Closing this in favor of #63 . I know it's a bit odd but I need to update the tests, so doing os to give myself a bit more control

**Comment by rfbird** [comment]
Closing and replacing with #63 that merges from a local branch on the repo. Generally I dislike this, but it let me run the tests using our gitlab checks too

**Pull request closed without merging**
