### PR TITLE
Support for in situ time average of fields

### PR DESCRIPTION
**Pull request by dnystrom1**
Added changes to src/vpic/dump.cc and src/vpic/vpic.h originally implemented by Brian Albright to allow passing of the field to be dumped via an optional argument to relevant functions.  The use case for this is to allow creation of a separate field to hold a time average of a given field which can then be time averaged in situ instead of dumping the field at a higher frequency and then performing the time average as a post-processing step.  This greatly reduces the amount of IO which needs to be performed and the number of file system inodes that need to be used for large scale runs performed by some users.  Use of an optional argument to the function allows for backward compatibility of existing input decks.

### CODE REVIEW

**Comment by dnystrom1** [comment]
So, I see this above.

This branch has no conflicts with the base branch
Merging can be performed automatically. 

And I just sent you email showing I can do a fresh clone of the devel branch and pull my
changes into it without any merge conflicts.  So, I am having trouble seeing what I have
done wrong and what needs to be done to fix it.

Dave

**Comment by dnystrom1** [comment]
And, I do not know what the "All checks have failed" message is complaining about.

What is the next step I need to do to make progress on getting this merged?

**Comment by dnystrom1** [comment]
Are you able to merge this now?

**Comment by petschge** [comment]
That header change would break every tool that is trying to parts binary field output, nor?

**Comment by dnystrom1** [comment]
No, not really.  The format of the file header remains unchanged but the user can now specify the
value of the timestep that is associated with a field dump.  For the case of a time averaged field,
the data in a field dump represents the average over several timesteps and it is likely more appropriate
for the timestep that is associated with that field be something like the timestep value for the middle of
the timestep range.  Previously, the timestep that would be dumped with the field data would be that of
the last timestep in the series.  It should be possible, even in the former case, to figure out what the middle
timestep value would be given the last timestep in the series and the number of timesteps in the series
but this eases the burden on the post-processing analysis.

So, there is a change to the argument list of the WRITE_HEADER_V0 macro that is not optional but I do
not believe that is in use by users although there is nothing to stop them if they wanted to.

So, my assessment is that there is no change to the file data format and there is no change that would break
a previously existing input deck.

**Comment by petschge** [comment]
Right. Sorry for the noise.

**Comment by dnystrom1** [comment]
NP.  The more eyes looking at this stuff, the better.  I thought the same thing when I first looked at the changes that Alex was proposing.

**Comment by rfbird** [comment]
> Are you able to merge this now?

I can, but for some reason I have to squash it (there is something odd in your history?)

**Comment by rfbird** [comment]
Can you rebase this off devel? You're trying to merge commits from 2018..

**Pull request closed without merging**
